creating sign-up endpoint
wolox-training/fm-express-js pull request #4
Opened 2021-11-03 17:47 UTC by f-medina

## Summary
- User sign-up endpoint

## Known Issues
No testing

## Trello Card
https://trello.com/c/BelrmZRS/35-sign-up

2021-11-18 15:57 UTC, jersonlopez requested changes

2021-11-18 15:57 UTC, jersonlopez commented on app/controllers/user.js
> +  newUser({ firstName, lastName, email, password })
Always that you use {} you should return something

2021-11-18 15:57 UTC, jersonlopez commented on app/controllers/user.js
> +  const { firstName, lastName, email, password } = req.body;
I think you can restrict the fields by applying destructuring in the service and keep the controller as clear as you can do it, some like this: 
```
exports.myController = (req, res, next) =>  
    myService(req.body)
      .then(...)
      .catch(...)
```

what do you think?

2021-11-18 15:57 UTC, jersonlopez commented on app/errors.js
> +exports.MAIL_EXIST_ERROR = 'validation_error';
this constant value is equal to `exports.VALIDATION_ERROR`

2021-11-18 15:57 UTC, jersonlopez commented on app/errors.js
> +exports.mailExistError = message => internalError(message, exports.VALIDATION_ERROR);
here you are passing a wrong `internalCode` because this error is for existing mails

2021-11-18 15:57 UTC, jersonlopez commented on app/models/user.js
> +  const encryptPassword = async userData => {
this method could be a helper, what do you think?

2021-11-18 15:57 UTC, jersonlopez commented on app/models/user.js
> +    const salt = await bcrypt.genSalt(15);
You should avoid using the magic numbers, I suggest to you put rounds number in an env var

2021-11-18 15:57 UTC, jersonlopez commented on app/models/user.js
> +  const matchPassword = password => bcrypt.compare(password, this.password);
same here

2021-11-18 15:57 UTC, jersonlopez commented on app/routes.js
> +  app.post('/new-user', validateSchemaAndFail(createUserSchema), newUser);
This endpoint is not using the HTTP rest standard, please read, please search about that and if you have any questions you always can type me by slack

2021-11-18 15:57 UTC, jersonlopez commented on app/schemas/users.js
> +      options: [/@(\.wolox\.com)|wolox\.(com(\.(ar|co|mx|con|cl)))?/],
what happens if in the future wolox opens a new country?

2021-11-29 17:12 UTC, jonnyalexbh approved these changes

2021-11-29 18:45 UTC, merged